Artifactory.cmake: validate the artifact 'upload version'
The artifactory-download script requires a specific format for the
version strings. Artifactory also has some restrictions on what format
the version string can have.

If we don't enforce the correct format here, then it's possible to
upload artifacts with bad names that cause the whole artifact caching
system to break for everyone.

The error that I saw after uploading an artifact with too many hyphens
in the version string was this:

    CMake Error at Artifactory.cmake:269 (message):
      ERROR: Expected to find main artifact buildroot-development-x86_64-sam-hash-confusion.rootfs.tar.gz in the
      list of files, but did not! Artifact files are:

        ...

You can trigger the new error checking code by running:

    cmake -DBUILD_SERIES=my-invalid-build-series

This also fixes some issues in the existing artifact version validation.
You can trigger this by setting stuff like:

    cmake -DARTIFACTS_VERSION=my/bad/version